# Grouping and Combining Web of Science and Scopus Files

This notebook focuses on grouping and combining records from Web of Science and Scopus files. The goal is to create a single CSV file that consolidates all records from multiple sources, which will be used for modeling in the next steps.

In [1]:
# Imports
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import os

# Var list global
key_words = []

### Create DataFrame Pandas with articles WOS records

In [ ]:
# Directory containing the .xls files
# directory = 'data/articles/scopus'

# dataframes = []

# # Iterate over all files in the specified folder
# for filename in os.listdir(directory):
#     if filename.endswith('.csv'):
#         file_path = os.path.join(directory, filename)
#         print(filename.split('.')[0])

ai

In [2]:
# Directory containing the .xls files
directory = 'data/articles/wos'

dataframes = []

# Iterate over all files in the specified folder
for filename in os.listdir(directory):
    if filename.endswith('.xls'):
        file_path = os.path.join(directory, filename)
        df = pd.read_excel(file_path)
        key_words.append(filename.split('.')[0])
        df['Source'] = directory.split('/')[-1]+'-'+filename.split('.')[0]
        dataframes.append(df)

# Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

# If duplicates based on the "Article Title" field, to remove!
df_wos = combined_df.drop_duplicates(subset=['Article Title'])
df_wos.reset_index(drop=True, inplace=True)

df_wos = df_wos[['Article Title','Authors','Publication Year','DOI','Abstract','Author Keywords','Publisher','Source','Times Cited, All Databases']]
df_wos.columns = ['Title','Authors','Year','DOI','Abstract','Keywords','Publisher','Source','Cited']
df_wos.head()

,Title,Authors,Year,DOI,Abstract,Keywords,Publisher,Source,Cited
0,Big-data AI analytics in value-chain innovatio...,"Zong, ZP; Anwar, MA; Khan, S; Asmi, F; Hussain, N",2025,10.1108/IMR-02-2024-0049,Purpose Despite great consensus on the positiv...,Big-data-based AI analytics; Digital affordanc...,EMERALD GROUP PUBLISHING LTD,wos-ai,0
1,Anthropomorphism in artificial intelligence: a...,"Gomes, S; Lopes, JM; Nogueira, E",2025,10.1186/s43093-025-00423-y,The expansion of brands adopting artificial in...,Artificial intelligence; Anthropomorphism; Cha...,SPRINGER,wos-ai,0
2,A Primer on Out-of-the-Box AI Marketing Mix Mo...,"Estevez, M; Ballestar, MT; Sainz, J",2025,10.1109/TEM.2024.3519172,Marketing mix modeling (MMM) optimizes budget ...,Biological system modeling; Artificial intelli...,IEEE-INST ELECTRICAL ELECTRONICS ENGINEERS INC,wos-ai,0
3,"Past, present and future of AI in marketing an...","Marvi, R; Foroudi, P; Cuomo, MT",2024,10.1108/JKM-07-2023-0634,PurposeThis paper aims to explore the intersec...,Artificial intelligence; Knowledge management;...,EMERALD GROUP PUBLISHING LTD,wos-ai,0
4,Unveiling user responses to AI-powered persona...,"Ding, L; Antonucci, G; Venditti, M",2024,10.1108/QMR-11-2023-0151,PurposeThis study aims to explore the impact o...,TikTok; Artificial intelligence; Short video; ...,EMERALD GROUP PUBLISHING LTD,wos-ai,0

In [3]:
len(df_wos)

538

In [ ]:
# df_wos.groupby('Source').count()

,Title,Authors,Year,DOI,Abstract,Keywords,Publisher,Cited
Source,,,,,,,,
wos-Internet of Things,9,9,9,9,9,9,9,9
wos-IoT,4,4,4,3,4,4,4,4
wos-ai,127,127,127,126,127,122,127,127
wos-artificial intelligence,69,69,69,68,69,67,69,69
wos-automation,13,13,13,13,13,12,13,13
wos-autonomous,28,28,28,27,27,23,28,28
wos-big data,150,150,150,147,150,144,150,150
wos-chatbot,5,5,5,5,5,5,5,5
wos-computer vision,1,1,1,1,1,1,1,1
wos-data mining,48,48,48,45,48,47,48,48
wos-data science,10,10,10,10,10,9,10,10
wos-fuzzy logic,19,19,19,17,19,19,19,19
wos-genetic algorithm,16,16,16,14,16,16,16,16
wos-k-means,16,16,16,15,16,16,16,16
wos-machine learning,47,47,47,47,47,45,47,47
wos-natural language processing,2,2,2,2,2,2,2,2
wos-neural network,40,40,40,38,40,38,40,40
wos-prediction,137,137,137,132,137,115,137,137
wos-recommendation,111,111,111,108,111,96,111,111
wos-robot,2,2,2,1,2,2,2,2
wos-smart technologies,1,1,1,1,1,1,1,1
wos-soft computing,2,2,2,2,2,2,2,2
wos-text mining,16,16,16,16,16,15,16,16

In [4]:
df_wos.groupby('Source').count()

,Title,Authors,Year,DOI,Abstract,Keywords,Publisher,Cited
Source,,,,,,,,
wos-Internet of Things,4,4,4,4,4,4,4,4
wos-ai,94,94,94,92,94,92,94,94
wos-artificial intelligence,50,50,50,50,50,49,50,50
wos-automation,6,6,6,6,6,6,6,6
wos-autonomous,12,12,12,11,12,11,12,12
wos-big data,95,95,95,93,95,91,95,95
wos-chatbot,4,4,4,4,4,3,4,4
wos-data mining,37,37,37,35,37,35,37,37
wos-data science,5,5,5,5,5,5,5,5
wos-fuzzy logic,15,15,15,13,15,15,15,15
wos-genetic algorithm,7,7,7,5,7,7,7,7
wos-k-means,19,19,19,18,19,19,19,19
wos-machine learning,30,30,30,29,30,28,30,30
wos-natural language processing,2,2,2,2,2,2,2,2
wos-neural network,16,16,16,14,16,16,16,16
wos-prediction,65,65,65,62,65,57,65,65
wos-recommendation,66,66,66,61,66,58,66,66
wos-smart technologies,2,2,2,2,2,2,2,2
wos-soft computing,2,2,2,2,2,2,2,2
wos-text mining,7,7,7,7,7,7,7,7

In [ ]:
# df_wos.to_excel('wos_artigos.xlsx')

In [5]:
df_wos.sort_values('Cited', ascending=False).head(20)

,Title,Authors,Year,DOI,Abstract,Keywords,Publisher,Source,Cited
525,Consumer decision making in online shopping en...,"Häubl, G; Trifts, V",2000,10.1287/mksc.19.1.4.15178,Despite the explosive growth of electronic com...,NaN,INST OPERATIONS RESEARCH MANAGEMENT SCIENCES,wos-recommendation,1015
459,Decision-making under uncertainty: Capturing d...,"Erdem, T; Keane, MP",1996,10.1287/mksc.15.1.1,We construct two models of the behavior of con...,NaN,INST OPERATIONS RESEARCH MANAGEMENT SCIENCES,wos-prediction,681
458,Consumption self-control by rationing purchase...,"Wertenbroch, K",1998,10.1287/mksc.17.4.317,Consumers' attempts to control their unwanted ...,intertemporal choice; pricing policy; product ...,INST OPERATIONS RESEARCH MANAGEMENT SCIENCES,wos-prediction,610
522,Reactance to recommendations: When unsolicited...,"Fitzsimons, GJ; Lehmann, DR",2004,10.1287/mksc.1030.0033,Recommendations often play a positive role in ...,recommendations; intelligent agents; decision ...,INFORMS,wos-recommendation,431
138,User generated content: the use of blogs for t...,"Akehurst, G",2009,10.1007/s11628-008-0054-2,As the World Wide Web has developed considerab...,User generated content; Blogs; Tourism; Travel...,SPRINGER HEIDELBERG,wos-artificial intelligence,312
447,WHAT'S ADVERTISING CONTENT WORTH? EVIDENCE FRO...,"Bertrand, M; Karlan, D; Mullainathan, S; Shafi...",2010,10.1162/qjec.2010.125.1.263,Firms spend billions of dollars developing adv...,NaN,OXFORD UNIV PRESS INC,wos-prediction,303
425,A new hybrid classification algorithm for cust...,"De Caigny, A; Coussement, K; De Bock, KW",2018,10.1016/j.ejor.2018.02.009,Decision trees and logistic regression are two...,OR in marketing; Hybrid algorithm; Customer ch...,ELSEVIER,wos-prediction,283
524,Market situation interpretation and response: ...,"White, JC; Varadarajan, PR; Dacin, PA",2003,10.1509/jmkg.67.3.63.18654,Improving marketing decision making requires a...,NaN,SAGE PUBLICATIONS INC,wos-recommendation,263
510,The effects of blogger recommendations on cust...,"Hsu, CL; Lin, JCC; Chiang, HS",2013,10.1108/10662241311295782,Purpose - Blogging has become part of a consum...,Blogging; Recommendations; Online shopping; Tr...,EMERALD GROUP PUBLISHING LTD,wos-recommendation,249
135,Online relationship marketing,"Steinhoff, L; Arli, D; Weaven, S; Kozlenkova, IV",2019,10.1007/s11747-018-0621-6,Online interactions have emerged as a dominant...,Relationship marketing; Relationship selling; ...,SPRINGER,wos-artificial intelligence,246
295,Integrating AHP and data mining for product re...,"Liu, DR; Shih, YY",2005,10.1016/j.im.2004.01.008,Product recommendation is a business activity ...,recommendation; marketing analytic hierarchy p...,ELSEVIER,wos-data mining,232
86,Machine learning and AI in marketing - Connect...,"Ma, LY; Sun, BH",2020,10.1016/j.ijresmar.2020.04.005,Artificial intelligence (AI) agents driven by ...,Artificial intelligence (AI); Machine learning...,ELSEVIER,wos-ai,226
328,Modeling the internet of things adoption barri...,"Kamble, SS; Gunasekaran, A; Parekh, H; Joshi, S",2019,10.1016/j.jretconser.2019.02.020,Internet of things (IoT) is estimated to play ...,Internet of things; Retail supply chain; ISM; ...,ELSEVIER SCI LTD,wos-Internet of Things,212
157,Futurizing smart service: implications for ser...,"Wünderlich, NV; Heinonen, K; Ostrom, AL; Patri...",2015,10.1108/JSM-01-2015-0040,Purpose - The purpose of this paper is to craf...,Connected services; Intelligent object; New se...,EMERALD GROUP PUBLISHING LTD,wos-autonomous,197
270,Using Data Sciences in Digital Marketing: Fram...,"Saura, JR",2021,10.1016/j.jik.2020.08.001,"In the last decade, the use of Data Sciences, ...",Data Sciences; Digital Marketing; Knowledge di...,ELSEVIER ESPANA,wos-data mining,191
520,Conceptualization and measurement of relations...,"Huntley, JK",2006,10.1016/j.indmarman.2005.05.011,Following over a decade of relationship market...,relationship quality; relationship marketing; ...,ELSEVIER SCIENCE INC,wos-recommendation,175
518,Recommendation systems with purchase data,"Bodapati, AV",2008,10.1509/jmkr.45.1.77,Many firms use decision tools called automatic...,customer relationship management; one-to-one m...,SAGE PUBLICATIONS INC,wos-recommendation,175
375,Consideration-set heuristics,"Hauser, JR",2014,10.1016/j.jbusres.2014.02.015,Consumers often choose products by first formi...,Consideration sets; Decision heuristics; Fast-...,ELSEVIER SCIENCE INC,wos-machine learning,175
127,An integrated artificial intelligence framewor...,"Bag, S; Gupta, S; Kumar, A; Sivarajah, U",2021,10.1016/j.indmarman.2020.12.001,This study examines the effect of big data pow...,Artificial intelligence; Big data; Knowledge m...,ELSEVIER SCIENCE INC,wos-artificial intelligence,169
373,Customer Acquisition via Display Advertising U...,"Schwartz, EM; Bradlow, ET; Fader, PS",2017,10.1287/mksc.2016.1023,Firms using online advertising regularly run e...,multi-armed bandit; online advertising; field ...,INFORMS,wos-machine learning,163

In [6]:
print(f'Number of articles in Web of Science Data Base: {len(df_wos)}')

Number of articles in Web of Science Data Base: 538

### Create DataFrame Pandas with Scopus records

In [7]:
# Directory containing the .xls files
directory = 'data/articles/scopus'

dataframes = []

# Iterate over all files in the specified folder
for filename in os.listdir(directory):
    if filename.endswith('.csv'):
        file_path = os.path.join(directory, filename)
        df = pd.read_csv(file_path)    
        df['Source'] = directory.split('/')[-1]+'-'+filename.split('.')[0]    
        dataframes.append(df)

# Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

# If duplicates based on the "Article Title" field, to remove!
df_scopus = combined_df.drop_duplicates(subset=['Title'])
df_scopus.reset_index(drop=True, inplace=True)

df_scopus = df_scopus[['Title','Authors','Year','DOI','Abstract','Author Keywords','Publisher','Source','Cited by']]
df_scopus.columns = ['Title','Authors','Year','DOI','Abstract','Keywords','Publisher','Source','Cited']

df_scopus.head()

,Title,Authors,Year,DOI,Abstract,Keywords,Publisher,Source,Cited
0,IMPACT OF HORTICULTURE ON THE SUSTAINABLE LIVE...,Mukherjee D.; Jena L.K.; Chakraborty S.; Debna...,2024,10.51599/ARE.2024.10.02.04,Purpose. The perishable nature of the horticul...,economics; horticulture; livelihood developmen...,Institute of Eastern European Research and Con...,scopus-ai,0
1,Out of the fog: fog computing-enabled AI to su...,Hornik J.; Ofir C.; Rachamim M.,2024,10.1007/s11301-024-00441-0,Marketing and consumer research use a variety ...,Artificial intelligence (AI); Digital marketin...,Springer Nature,scopus-ai,1
2,The Role of AI in Enhancing Marketing Communic...,Isnaini S.; Muslimin A.I.,2024,10.11114/smc.v12i4.7013,This research delves into the transformative i...,artificial intelligence; development; higher e...,Redfame Publishing Inc.,scopus-ai,0
3,Deploying artificial intelligence in services ...,Hermann E.; Williams G.Y.; Puntoni S.,2024,10.1007/s11747-023-00986-8,Despite offering substantial opportunities to ...,Artificial intelligence; Ethics; Justice; Serv...,Springer,scopus-ai,11
4,THE IMPACT OF BRAND-VOICE INTEGRATION AND ARTI...,Murár P.; Kubovics M.; Jurišová V.,2024,10.34135/COMMUNICATIONTODAY.2024.VOL.15.NO.1.4,Corporate identity plays an important role in ...,artificial intelligence; brand communication; ...,"University of SS. Cyril and Methodius, Faculty...",scopus-ai,3

In [8]:
print(f'Number of articles in Scopus Data Base: {len(df_scopus)}')

Number of articles in Scopus Data Base: 1754

### Group WOS and Scorpus

In [9]:
df_all = pd.concat([df_scopus,df_wos])
df_all.head()

,Title,Authors,Year,DOI,Abstract,Keywords,Publisher,Source,Cited
0,IMPACT OF HORTICULTURE ON THE SUSTAINABLE LIVE...,Mukherjee D.; Jena L.K.; Chakraborty S.; Debna...,2024,10.51599/ARE.2024.10.02.04,Purpose. The perishable nature of the horticul...,economics; horticulture; livelihood developmen...,Institute of Eastern European Research and Con...,scopus-ai,0
1,Out of the fog: fog computing-enabled AI to su...,Hornik J.; Ofir C.; Rachamim M.,2024,10.1007/s11301-024-00441-0,Marketing and consumer research use a variety ...,Artificial intelligence (AI); Digital marketin...,Springer Nature,scopus-ai,1
2,The Role of AI in Enhancing Marketing Communic...,Isnaini S.; Muslimin A.I.,2024,10.11114/smc.v12i4.7013,This research delves into the transformative i...,artificial intelligence; development; higher e...,Redfame Publishing Inc.,scopus-ai,0
3,Deploying artificial intelligence in services ...,Hermann E.; Williams G.Y.; Puntoni S.,2024,10.1007/s11747-023-00986-8,Despite offering substantial opportunities to ...,Artificial intelligence; Ethics; Justice; Serv...,Springer,scopus-ai,11
4,THE IMPACT OF BRAND-VOICE INTEGRATION AND ARTI...,Murár P.; Kubovics M.; Jurišová V.,2024,10.34135/COMMUNICATIONTODAY.2024.VOL.15.NO.1.4,Corporate identity plays an important role in ...,artificial intelligence; brand communication; ...,"University of SS. Cyril and Methodius, Faculty...",scopus-ai,3

In [10]:
print(f'Number of articles in Scopus and Web of Science Data Base: {len(df_all)}')

Number of articles in Scopus and Web of Science Data Base: 2292

In [11]:
# Remove duplicate
df_all = df_all.drop_duplicates(subset=['Title'])

# Remove empty
df_all = df_all[~df_all['Abstract'].isna()]

df_all.reset_index(inplace=True, drop=True)

print(f'Number of articles less duplicates and empty abstract: {len(df_all)}')

Number of articles less duplicates and empty abstract: 2043

### Save all data in .csv

In [12]:
df_all.to_csv('data/articles/all_articles.csv', index=False)